-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 15:37:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pandawdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pandawdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pandawdb` DEFAULT CHARACTER SET utf8 ;
USE `pandawdb` ;

-- -----------------------------------------------------
-- Table `pandawdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandawdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pandawdb`.`moneyflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pandawdb`.`moneyflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `isIncome` INT NULL,
  `timeOfAdd` DATETIME NOT NULL,
  `currentWealth` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_moneyflow_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_moneyflow_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `pandawdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
